Repository Matroska-Org/libmatroska, pull requests merged in 2022-10, with the labels that each got.

#77 bump soname to 8 due to ABI-breaking changes & bump version number
  CMakeLists.txt
  NEWS.md
  matroska/KaxVersion.h
  src/KaxVersion.cpp
Labels: abi-break

#83 [1.x] build actions on 1.x should checkout the libebml v1.x branch
  .github/workflows/linux-gcc10.yaml
  .github/workflows/linux.yaml
  .github/workflows/macos.yaml
  .github/workflows/windows.yaml
Labels: build-system

#84 [1.x] do 1.x build actions when pushing to the v1.x branch
  .github/workflows/linux-gcc10.yaml
  .github/workflows/linux.yaml
  .github/workflows/macos.yaml
  .github/workflows/windows.yaml
Labels: build-system

#89 remove confusing SVN version tag
  matroska/KaxChapters.h
  matroska/KaxContexts.h
  matroska/KaxDefines.h
  matroska/KaxInfoData.h
  matroska/KaxSeekHead.h
  matroska/KaxTag.h
  matroska/KaxTrackVideo.h
  src/FileKax.cpp
  src/KaxAttached.cpp
  src/KaxAttachments.cpp
  src/KaxBlock.cpp
  src/KaxBlockData.cpp
  src/KaxCluster.cpp
  src/KaxContexts.cpp
  src/KaxCues.cpp
  src/KaxCuesData.cpp
  src/KaxInfoData.cpp
  src/KaxSeekHead.cpp
  src/KaxSegment.cpp
  src/KaxTracks.cpp
  src/KaxVersion.cpp
  test/ebml/test0.cpp
  test/ebml/test00.cpp
  test/mux/test6.cpp
  test/mux/test8.cpp
  test/tags/test9.cpp
  test/utf8/test5.cpp
Labels: enhancement

#96 build test examples
  .github/workflows/linux-gcc10.yaml
  .github/workflows/linux.yaml
  .github/workflows/macos.yaml
  .github/workflows/windows.yaml
  CMakeLists.txt
  test/ebml/test00.cpp
  test/mux/test8.cpp
Labels: build-system

#95 clean access to protected members
  src/KaxBlock.cpp
  src/KaxCluster.cpp
Labels: enhancement

#99 KaxSemantic: update with latest spectool (using clean enum text)
  matroska/KaxSemantic.h
Labels: enhancement
